# Generated by Django 6.0.3 on 2026-04-07 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_rating_product_reviews'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('all', 'All Products'), ('smart_panels', 'Smart Central Control Panels'), ('smart_lighting', 'Smart Lighting'), ('smart_switches', 'Smart Switches'), ('home_security', 'Home & Security Sensors')], max_length=50),
        ),
    ]
