# Generated by Django 6.0.3 on 2026-04-12 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_recommended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='recommended',
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.IntegerField(max_length=10),
        ),
    ]
