# Generated by Django 6.0.3 on 2026-06-18 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_review'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='product',
            name='reviews',
        ),
    ]
