# Generated by Django 6.0.3 on 2026-06-18 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_remove_product_rating_remove_product_reviews'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
